[wandb]
project = "Rodent-Run-With-Decoder"
run_name = "Test-{NOW}"

[rollout]
n_envs = 4096
reset_on_epoch_start = false
n_epochs = 500000
n_steps_per_epoch = 16
use_mpi = true

[network]
actor_size = [1024]
critic_size = [1024, 1024]
sigma_min = 0.01
sigma_max = 0.5

[physics]
spawn_z_offset = 0.01
n_physics_steps = 5
timestep = 0.002
torque_control = true
hip_mods = false
body_scale = 1.0
min_torso_z = 0.035
foot_mods = true

[reward]
control_cost = 0.005
energy_cost = 0.01
alive_bonus = 0.1
    [reward.falloff]
    speed = 1.0

[run]
decoder_wandb_run_id = "zf8zs3kq"
min_target_speed = 0.5
max_target_speed = 5.0
episode_length = 500

[training]
checkpoint_interval = 5000
loss_weight_critic = 0.5
loss_weight_actor = 1.0
loss_weight_entropy = -0.2
learning_rate = 0.0001
n_miniepochs = 1
gamma = 0.95
loss_weight_kl = 0.1
lambda = 0.95
clip_range = 0.2
